#!/bin/bash

ROOT=`hg root`

function die {
    echo "* ERROR *"
    echo "* $@"
    exit 1
}

function get {
    echo $2
    wget -q $1 -O $ROOT/$2 || die $1 $2
}

# regenerate gitignore file
echo gitignore
tail -n +3 $ROOT/hgignore > $ROOT/gitignore

# vundle
get https://github.com/gmarik/Vundle.vim/archive/master.zip vundle.zip
rm -Rf $ROOT/vim/vundle
unzip -q $ROOT/vundle.zip
mv $ROOT/Vundle.vim-master $ROOT/vim/vundle
rm $ROOT/vundle.zip

# hg bash-autocompltion
get http://selenic.com/hg/raw-file/tip/contrib/bash_completion bash-completion/mercurial.sh

# hg vim plugin
get http://selenic.com/hg/raw-file/tip/contrib/vim tmp
sed -i '/^$/d' $ROOT/tmp
for f in `cat $ROOT/tmp | awk '{print $3}'`
do
    get http://selenic.com/hg/raw-file/tip/contrib/vim/$f vim/plugin/$f
done
rm $ROOT/tmp

echo "* DONE! *"
