" general {{{
syntax on
" }}}
" options {{{
"  1 important
set nocompatible
" 10 GUI
if has('gui_running')
    set guioptions-=T " no toolbar
endif
" 15 tabs and indenting
set tabstop=4
set shiftwidth=4
set expandtab
" 16 folding
set foldcolumn=2 " columns on right side of screen to show fold level
set foldmethod=marker " {}x3 to fold
" }}}
" mappings {{{
" ; => :
map ; :
" fast jump to head and tail of line
map H ^
map L $
" fold/unfold with space
map <space> za
" toggle line numbers
nmap <silent> <F1> :set number!<CR>
imap <silent> <F1> <ESC>:set number!<CR>a
nmap <silent> <C-F1> :set number!<CR>
imap <silent> <C-F1> <ESC>:set number!<CR>a
" }}}
