" general {{{
syntax on
" leader key
let mapleader = ","
let maplocalleader = "\\"
" }}}
" options {{{
"  1 important
set nocompatible
"  2 moving around, searching and patterns
set incsearch
set ignorecase
set smartcase
" 10 GUI
if has('gui_running')
    set guifont="Source Code Pro 9"
    set guioptions-=T " no toolbar
endif
" 15 tabs and indenting
set tabstop=4
set shiftwidth=4
set expandtab " convert tab to spaces
" 16 folding
set foldcolumn=2 " columns on right side of screen to show fold level
set foldmethod=marker " {}x3 to fold
" }}}
" vundle {{{
filetype off
set runtimepath+=~/.vim/bundle/vundle
call vundle#rc()
Bundle "gmarik/vundle"

" syntax and other crap for markdown files
Bundle "tpope/vim-markdown"
" colorscheme
Bundle "veloce/vim-aldmeris"

filetype plugin on
filetype indent on
" }}}
" mappings {{{
" ; => :
map ; :
" jj => <ESC>
imap jj <ESC>
" fast jump to head and tail of line
map H ^
map L $
" fold/unfold with space
map <space> za
" toggle line numbers
nmap <silent> <F1> :set number!<CR>
imap <silent> <F1> <ESC>:set number!<CR>a
nmap <silent> <C-F1> :set number!<CR>
imap <silent> <C-F1> <ESC>:set number!<CR>a
" quickly change filetype
map <leader>ft  :set filetype=
" sudo write
cmap W!! w !sudo tee % >/dev/null
" }}}
" autocmd {{{
" markdown
autocmd FileType markdown setlocal shiftwidth=2 tabstop=2
" }}}
" commands {{{
command GEDIT execute "!gedit '%:p' &"
" }}}
" color {{{
if has("gui_running")
    colorscheme aldmeris
endif
" }}}
" if cwd is ~ change it to ~/Workspace {{{
if getcwd() == expand('$HOME')
    cd ~/Workspace
endif
" }}}
