snippet #! "init" b
FROM ${1:ubuntu${2::14.04}}

MAINTAINER Ali Vakilzade <ali.vakilzade@gmail.com>

$3
endsnippet

snippet "[aA]" "ADD" rb
ADD $1
endsnippet

snippet "[cC]" "CMD" rb
CMD $1
endsnippet

snippet "[rR]" "RUN" rb
RUN $1
endsnippet

